INSERT INTO expenses(name, tooltip)
VALUES
  ('Sterilization', null),
  ('Medical consultation and health check-up (3 visits)', null),
  ('Vaccines (excluding health check-up)', json '[{ "text": "According to the Ordre des médecins vétérinaires du Québec (OMVQ), a vaccination must be preceded by a complete physical examination by the veterinarian (Code of Ethics of Veterinarians, section II, article 9, paragraph 3).", "link": "https://www.cvetc.com/en-ca/resources/vaccination-guide-for-cats" }]'),
  ('Fecal exam', null),
  ('Screening blood tests', null),
  ('Regulatory tag', json '[{ "text": "Varies by municipality."}]'),
  ('Basic deworming', null),
  ('High-quality dry food', null),
  ('Basic accessories (harness, leash, bowls, brush, nail clippers, etc.)', null),
  ('Litter', null),
  ('Prevention against external and internal parasites', json '[{ "text": "Parasite prevention needs will vary greatly depending on your pet''s environment, lifestyle and lifestyle and outdoor activities. So it''s important to discuss this subject with your veterinary team."}]'),
  ('Addition of high-quality wet food', json '[{ "text": "In addition to dry food."}]'),
  ('Microchip implantation (implant not included)', json '[{ "text": "A good option is to have it done at the same time as a routine anaesthesia (e.g.: sterilization).", "link": "https://www.vetetnous.com/en/tips/demystifying-the-microchip-cat/" }, { "text": "Microchipping is now mandatory for cats and dogs in many Quebec municipalities and cities, including Montreal and Laval.", "link": "https://www.mondou.com/en-CA/blogs/advice/dog/microchip-everything-you-need-to-know-ad44.html"}]'),
  ('Insurance program (basic)', json '[{ "text": "The amount is for information only; costs and coverage may vary from one company to another. And depending on the age of the animal at the start of the contract, the younger the animal, the less expensive it is."}]'),
  ('Medical consultation and health check-up', null),
  ('Renewal of basic accessories (harness, leash, bowls, brush, nail clippers, etc.)', null),
  ('Annual preventive screening (feces/blood)', null),
  ('Laboratory examination and screening', json '[{ "text": "Depending on the specific medical needs of each animal. This is discussed and decided with your veterinary team."}]'),
  ('Dental prophylaxis', json '[{ "text": "Scaling and polishing under general anesthesia."}]'),
  ('Dental X-rays', json '[{ "text": "Dental care needs will vary greatly depending on your pet''s breed and genetics. They can be performed every 1 to 2 years, depending on the individual patient."}]'),
  ('Medical consultation and health check-up (2 per year)', null),
  ('High-quality dry food +/- dietary supplements', null),
  ('Geriatric blood test', null);