INSERT INTO expenses(name)
VALUES
  ('Sterilization'),
  ('Medical consultation and health check-up (3 visits)'),
  ('Vaccines (excluding health check-up)'),
  ('Fecal exam'),
  ('Screening blood tests'),
  ('Regulatory tag'),
  ('Basic deworming'),
  ('High-quality dry food'),
  ('Basic accessories (harness, leash, bowls, brush, nail clippers, etc.)'),
  ('Litter'),
  ('Prevention against external and internal parasites'),
  ('Addition of high-quality wet food'),
  ('Microchip implantation (implant not included)'),
  ('Insurance program (basic)'),
  ('Medical consultation and health check-up'),
  ('Renewal of basic accessories (harness, leash, bowls, brush, nail clippers, etc.)'),
  ('Annual preventive screening (feces/blood)'),
  ('Laboratory examination and screening'),
  ('Dental prophylaxis'),
  ('Dental X-rays'),
  ('Medical consultation and health check-up (2 per year)'),
  ('High-quality dry food +/- dietary supplements'),
  ('Geriatric blood test');