INSERT INTO expenses(name, tooltip)
VALUES
  ('Sterilization', null),
  ('Medical consultation and health check-up (3 visits)', null),
  ('Vaccines (excluding health check-up)', json '[{ "text": "According to the Ordre des médecins vétérinaires duQuébec (OMVQ), a vaccination must be preceded by a complete physical examination by the veterinarian (Code of Ethics of Veterinarians, section II, article 9, paragraph 3).", "link": "https://www.cvetc.com/en-ca/resources/vaccination-guide-for-cats" }]'),
  ('Fecal exam', null),
  ('Screening blood tests', null),
  ('Regulatory tag', null),
  ('Basic deworming', null),
  ('High-quality dry food', null),
  ('Basic accessories (harness, leash, bowls, brush, nail clippers, etc.)', null),
  ('Litter', null),
  ('Prevention against external and internal parasites', null),
  ('Addition of high-quality wet food', null),
  ('Microchip implantation (implant not included)', json '[{ "text": "A good option is to have it done at the same time as a routine anaesthesia (e.g.: sterilization).", "link": "https://www.vetetnous.com/en/tips/demystifying-the-microchip-cat/" }, { "text": "Microchipping is now mandatory for cats and dogs in many Quebec municipalities and cities, including Montreal and Laval.", "link": "https://www.mondou.com/en-CA/blogs/advice/dog/microchip-everything-you-need-to-know-ad44.html"}]'),
  ('Insurance program (basic)', null),
  ('Medical consultation and health check-up', null),
  ('Renewal of basic accessories (harness, leash, bowls, brush, nail clippers, etc.)', null),
  ('Annual preventive screening (feces/blood)', null),
  ('Laboratory examination and screening', null),
  ('Dental prophylaxis', null),
  ('Dental X-rays', null),
  ('Medical consultation and health check-up (2 per year)', null),
  ('High-quality dry food +/- dietary supplements', null),
  ('Geriatric blood test', null);