INSERT INTO expenses(name)
VALUES
  (1, 'Medical consultation and health check-up (3 visits)'),
  (2, 'Vaccines (excluding health check-up)'),
  (3, 'Fecal exam'),
  (4, 'Screening blood tests'),
  (5, 'Regulatory tag'),
  (6, 'Basic deworming'),
  (7, 'High-quality dry food'),
  (8, 'Basic accessories (harness, leash, bowls, brush, nail clippers, etc.)'),
  (9, 'Litter'),
  (10, 'Prevention against external and internal parasites'),
  (11, 'Addition of high-quality wet food'),
  (12, 'Microchip implantation (implant not included)'),
  (13, 'Insurance program (basic)'),
  (14, 'Medical consultation and health check-up'),
  (15, 'Renewal of basic accessories (harness, leash, bowls, brush, nail clippers, etc.)'),
  (16, 'Annual preventive screening (feces/blood)'),
  (17, 'Laboratory examination and screening'),
  (18, 'Dental prophylaxis'),
  (19, 'Dental X-rays'),
  (20, 'Medical consultation and health check-up (2 per year)'),
  (21, 'High-quality dry food +/- dietary supplements'),
  (22, 'Geriatric blood test');